[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino

upload_protocol = serial
monitor_speed = 115200

board_build.f_cpu = 72000000L

build_flags = 
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D SERIAL_UART_INSTANCE=1
    -D USART1_TX_PIN=PA9
    -D USART1_RX_PIN=PA10

lib_deps = 
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit Unified Sensor
    bblanchon/ArduinoJson@^7.2.0