; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = serial
monitor_speed = 115200
board_build.f_cpu = 72000000L
build_flags = 
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-D SERIAL_UART_INSTANCE=1
	-D USART1_TX_PIN=PA9
	-D USART1_RX_PIN=PA10
lib_deps = 
	adafruit/Adafruit BME280 Library
	adafruit/Adafruit Unified Sensor
	bblanchon/ArduinoJson@^7.2.0
	z3t0/IRremote@^4.7.1
